desc 'Generate tags page'

task :projects do
  require 'xmlsimple'
  work = File.open("work.xml")
  data = XmlSimple.xml_in(work)
  html = ''
  brief_html = ''

  i = 0
  data['entry'].each do |entry|

    html << <<-PROJECT 
      <div class='Project'>
        <h1><a href='#{entry['link'][0]['href']}'>#{entry['title']}</a></h1>
        <div class='Summary'>#{entry['summary']}</div>
        <div><span class='Date'>Release:</span>#{entry['updated']}</div>
        <div><span class='URL'>URL:</span><a href='#{entry['link'][0]['href']}'>#{entry['link'][0]['href']}</a></div>
      </div>
    PROJECT

    if i<3
      brief_html << <<-PROJECT 
        <div class='Project'>
          <a class='ProjectName' href='#{entry['link'][0]['href']}'><span>#{entry['title']}:</span></a>
          #{entry['summary']}
        </div>
      PROJECT
    end
    
    i+=1

  end

  File.open("_includes/projects.html", 'w+') do |file|
    file.puts html
  end

  File.open("_includes/projects_brief.html", 'w+') do |file|
    file.puts brief_html
  end

end

task :tags do
  puts "Generating tags..."
  require 'rubygems'
  require 'jekyll'
  include Jekyll::Filters
  
  options = Jekyll.configuration({})
  site = Jekyll::Site.new(options)
  site.read_posts('')
  site.categories.sort.each do |category, posts|
    html = ''
    html << <<-HEAD
---
layout: default
title: Postings tagged "#{category}"
---
    <div class='List Content'>
    <h3 id="#{category}">Postings tagged "#{category}"</h1>
    <ul>
    HEAD

    posts.each do |post|
      post_data = post.to_liquid
      html << <<-POST
        <li><a href='{{ site.url }}#{ post.url }'>#{ post_data['title'] }</a></li>
      POST
    end

    html << <<-FOOT
    </div>
    FOOT

    File.open("tags/#{category}.html", 'w+') do |file|
      file.puts html
    end
  end

  html = '<div class="TagCloud">'
  site.categories.sort.each do |category, posts|
    rank = Integer(posts.count*1.5)
    size = 12+rank
    rgb = [rand(50),rand(50),rand(50)]
    rgb[rand(3)] += rank*20
    html << "<a href='{{ site.url }}/tags/#{category}.html' class='Tag' style='font-size:#{size}px; color:rgb(#{rgb[0]},#{rgb[1]},#{rgb[2]})'>#{category}</a>"
  end
  html << '</div>'
  File.open("_includes/tagcloud.html",'w+') do |file|
    file.puts html
  end

  puts 'Done.'

end

